# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.9'

services:
  task-management-backend:
    container_name: task-management-backend
    image: task-management-backend-dotnet
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      CONNECTION_STRING: mongodb://TaskManagement:Password1@task-management-db:27017/TaskManagement
      DB_COLLECTION: projects
      DB_NAME: TaskManagement
    ports:
      - 4000:4000
  task-management-db:
    container_name: task-management-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Password1
    ports:
      - 27017:27017

  
